name: Feature request
description: Suggest an idea for Theme Switcher
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Thanks for suggesting an idea!
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the problem or limitation you're running into.
    validations:
      required: true    
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false    
